### ISSUE TITLE
Cannot log into default account or created account. Incorrect password.

### ISSUE THREAD

**Issue by soitchy** [TheDarkBomber/lirix#2]
Testing on VirtualBox currently, after an EZInstall, I cannot log into either the default main user aamoo with the default password, nor can I log into a created account. The log in manager just says "Your password is incorrect. Please try again."

I am sure I am typing the passwords correct. I used almost all default options during the EZInstall. Using the US keyboard layout and tried with simple QWERTY safe passwords. No luck.

I booted into root and verified that both users are in /etc/passwd and /etc/shadow.

From root, I switched to the user account and changed the password via passwd. Rebooting and attempting to log in results in the same error.

**Comment by soitchy** [comment]
Some additional info after digging.

After chrooting into the install and creating a root password, I can log in to the root user.

From the log in screen, using ctrl + alt + F2 to revert to tty2, I can log in with the root user. I cannot log in to any other user in tty2.

I have tried creating new users with useradd and still cannot log into these users in tty2 nor the log in manager.

Looking at the journal, I don't see any strangeness during the login attempts other than "authentication failure."

**Comment by soitchy** [comment]
I have solved the issue. Users do not have a valid login shell assigned to them.

For anyone in the future that has this problem:

To change the login shell, chroot into the partition with Lirix or log into a root account then run the command `chsh -s /bin/bash $user` where $user refers to your user account name. Reboot. You should be able to log into your user account now.

**Comment by mood-fm** [comment]
Could you elaborate, in detail, on what it is you did to make it work? In particular, could you explain in a way someone with limited experience on Linux could understand?
