### ISSUE TITLE
Password issues during install

### ISSUE THREAD

**Issue by mattson62** [TheDarkBomber/lirix#4]
I saw a video on lirix and wanted to try it, very cool! Install went well overall on virtual box until time login.It didn't approve my password.So i reinstalled careful to double check my typing when setting user name and password.After install complete,time to log in...username is correct just as i type it during install,carefully watching my typing for password,it rejects it.So I reinstalled several times even tried the default machine,default user name,and default password same results.I tried typing nothing at all for username and password hoping it go to the defaults,then i tried root as username and password.I appreciate any help! thanks!

**Comment by x7f15h7x** [comment]
I second this issue, it's rendering the OS unusable, if someone has any recommendations

it would be much appreciated.
